# Site settings
url: "https://coinstra.com"
#url: "//localhost:4000"   # activate this to test on your localhost
author: "BlinkTrade"
baseurl: ""
deploy_version: "HEAD"

exchange: "coinstra"
exchange_logo: "coinstra"

default_country_code: "AU"
blinktrade_broker_id: 7 

#blinktrade_backend_api: "api.blinktrade.com"
blinktrade_backend_api: "api.testnet.blinktrade.com"
#blinktrade_backend_api: "localhost"
google_analytics_id: "UA-58087670-1"
zopim_key: "2gaAsPMIc8hKki6yBZQHVXoLNwsWomYF"


# Build settings
markdown: kramdown


languages: ["en_US", "es", "pt_BR", "ro"]

exclude:     [ "jsdev", "LICENSE", "README.md", "config.rb", "deploy.sh", "build_javascript.sh" ]
source:      .
destination: ./_site
plugins:     ./_plugins
paginate:    5
paginate_path: "post/page:num"
permalink:     /post/:title/
